FROM openjdk:17-alpine
MAINTAINER Grisha
COPY build/libs/SensorsStatisticService-0.0.1-SNAPSHOT.jar SensorsStatisticService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/SensorsStatisticService-0.0.1-SNAPSHOT.jar"]