#PORT
server:
  port: 8081

app:
  keycloak:
    url: http://localhost:8080/
    realm: kc_demo-realm

#check acces token
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/kc_demo-realm/protocol/openid-connect/certs
      client:
        registration:
          sensors-client:
            client-id: sensor-statistics-client
            client-secret: x1vxdY2FmALgtGTYMdQz1YM6366r5LhA
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri:  http://keycloak:8080/realms/${app.keycloak.realm}/protocol/openid-connect/token

  datasource:
    url: jdbc:postgresql://db_statistics:5432/sensor_statistics
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate.ddl-auto: validate

  liquibase:
    enabled: true
    default-schema: public
    change-log: db/changelog/db.changelog-master.yaml

